development:
  adapter: mysql2
  database: shopvibe_dev
  username: root
  password: 
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: shopvibe_test
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: shopvibe_production
  pool: 5
  timeout: 5000
